CREATE EXTERNAL TABLE IF NOT EXISTS assist_prime_NNN (
    award_id_fain STRING,
    modification_number STRING,
    award_id_uri STRING,
    sai_number STRING,
    federal_action_obligation STRING,
    non_federal_funding_amount DECIMAL,
    total_funding_amount DECIMAL,
    face_value_of_loan DECIMAL,
    original_subsidy_cost DECIMAL,
    total_subsidy_cost DECIMAL,
    total_loan_value DECIMAL,
    action_date TIMESTAMP,
    period_of_performance_start_date TIMESTAMP,
    period_of_performance_current_end_date TIMESTAMP,
    awarding_agency_code STRING,
    awarding_agency_name STRING,
    awarding_sub_agency_code STRING,
    awarding_sub_agency_name STRING,
    awarding_office_code STRING,
    awarding_office_name STRING,
    funding_agency_code STRING,
    funding_agency_name STRING,
    funding_sub_agency_code STRING,
    funding_sub_agency_name STRING,
    funding_office_code STRING,
    funding_office_name STRING,
    recipient_duns STRING,
    recipient_name STRING,
    recipient_parent_name STRING,
    recipient_parent_duns STRING,
    recipient_country_code STRING,
    recipient_country_name STRING,
    recipient_address_line_1 STRING,
    recipient_address_line_2 STRING,
    recipient_city_code STRING,
    recipient_city_name STRING,
    recipient_county_code STRING,
    recipient_county_name STRING,
    recipient_state_code STRING,
    recipient_state_name STRING,
    recipient_zip_code STRING,
    recipient_zip_last_4_code STRING,
    recipient_congressional_district STRING,
    recipient_foreign_city_name STRING,
    recipient_foreign_province_name STRING,
    recipient_foreign_postal_code STRING,
    primary_place_of_performance_country_code STRING,
    primary_place_of_performance_country_name STRING,
    primary_place_of_performance_code STRING,
    primary_place_of_performance_city_name STRING,
    primary_place_of_performance_county_code STRING,
    primary_place_of_performance_county_name STRING,
    primary_place_of_performance_state_name STRING,
    primary_place_of_performance_zip_4 STRING,
    primary_place_of_performance_congressional_district STRING,
    primary_place_of_performance_foreign_location STRING,
    cfda_number STRING,
    cfda_title STRING,
    assistance_type_code STRING,
    assistance_type_description STRING,
    award_description STRING,
    business_funds_indicator_code STRING,
    business_funds_indicator_description STRING,
    business_types_code STRING,
    business_types_description STRING,
    correction_delete_indicator_code STRING,
    correction_delete_indicator_description STRING,
    action_type_code STRING,
    action_type_description STRING,
    record_type_code STRING,
    record_type_description STRING,
    last_modified_date TIMESTAMP
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
    "separatorChar" = ",",
    "quoteChar" = "\""
)
STORED AS TEXTFILE
LOCATION '/user/svallej5/_project/data/assist_prime/partNNN/'
TBLPROPERTIES ('skip.header.line.count'='1');
